apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-enemy-bo
spec:
  replicas: 1
  selector:
    matchLabels:
      app : public-enemy-bo
  template:
    metadata:
      labels:
        app : public-enemy-bo
    spec:
      containers:
        - name: public-enemy-bo
          image: inseefr/public-enemy-back-office:0.0.1-SNAPSHOT
        



